# Generated by Django 5.0.2 on 2024-10-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_comicsmangas_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicsmangas',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
