# Generated by Django 5.0.2 on 2024-02-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicsmangas',
            name='cover_imgs',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='comicsmangas',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='comicsmangas',
            name='synopsis',
            field=models.TextField(max_length=800, null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='comicsmangas',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
