# Generated by Django 5.0.2 on 2024-02-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_comicsmangas_cover_imgs_alter_comicsmangas_cover_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicsmangas',
            name='cover_imgs',
        ),
    ]
