# Generated by Django 5.0.2 on 2024-02-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_remove_comicsmangas_cover_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytype',
            name='category',
        ),
    ]
