# Generated by Django 5.0.2 on 2024-02-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_categories_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
