# Generated by Django 5.0.2 on 2024-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0014_remove_order_items_order_address_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('LP', 'La Paz'), ('CBB', 'Cochabamba'), ('SCZ', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('CH', 'Chuquisaca'), ('BE', 'Beni'), ('PD', 'Pando'), ('LP', 'El Alto')], max_length=100),
        ),
    ]
