# Generated by Django 5.0.2 on 2024-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0018_remove_order_address_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Bolivia', 'Bolivia')], default='Bolivia', max_length=100),
        ),
    ]
