# Generated by Django 5.0.2 on 2024-02-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0019_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.IntegerField(choices=[(0, 'Recojer en Tienda (Gratis)'), (10, 'Envio de Tienda (+10 Bs)')], default=0),
        ),
    ]
