# Generated by Django 5.0.2 on 2024-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0020_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost_applied',
            field=models.BooleanField(default=False),
        ),
    ]
