# Generated by Django 5.0.2 on 2024-02-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0022_order_shipping_method_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost_applied',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
