# Generated by Django 5.0.2 on 2024-02-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0023_remove_order_shipping_cost_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost_applied',
            field=models.BooleanField(default=False),
        ),
    ]
