# Generated by Django 5.0.2 on 2024-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0024_order_shipping_cost_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('LP', 'La Paz'), ('CBB', 'Cochabamba'), ('SCZ', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('CH', 'Chuquisaca'), ('BE', 'Beni'), ('PD', 'Pando'), ('El Alto', 'El Alto')], max_length=100),
        ),
    ]
