# Generated by Django 5.0.2 on 2024-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0025_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Mercado Libre', 'Mercado Libre'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
