# Generated by Django 5.0.2 on 2024-02-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0026_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='included_in_order',
            field=models.BooleanField(default=False),
        ),
    ]
