# Generated by Django 5.0.2 on 2024-02-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0029_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Completado', 'Completado')], default='Pendiente', max_length=50),
        ),
    ]
