# Generated by Django 5.0.2 on 2024-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0030_order_delivered_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicsmangas',
            name='category',
        ),
        migrations.AddField(
            model_name='comicsmangas',
            name='category',
            field=models.ManyToManyField(to='myapp1.categories'),
        ),
    ]
