# Generated by Django 5.0.2 on 2024-09-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0032_remove_comicsmangas_theme_comicsmangas_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='comicsmangas',
            name='author',
        ),
        migrations.AddField(
            model_name='comicsmangas',
            name='author',
            field=models.ManyToManyField(to='myapp1.author'),
        ),
    ]
