# Generated by Django 5.0.2 on 2024-10-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0034_alter_comicsmangas_title_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=110),
        ),
    ]
