# Generated by Django 5.0.2 on 2024-10-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0035_alter_customuser_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
